export const sectionStyles = {
  page: {
    fontFamily: "'Segoe UI', system-ui, sans-serif",
    backgroundColor: '#fff',
    padding: '48px 0 72px',
  },
  container: {
    maxWidth: '1160px',
    margin: '0 auto',
    padding: '0 32px',
  },
  headerRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: '6px',
    flexWrap: 'wrap',
    gap: '16px',
  },
  sectionRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    margin: '24px 0 32px',
    flexWrap: 'wrap',
    gap: '16px',
  },
  title: {
    fontFamily: "'Playfair Display', Georgia, serif",
    fontSize: 'clamp(28px, 4vw, 44px)',
    fontWeight: '800',
    color: '#0f1923',
    margin: '0 0 10px',
    lineHeight: '1.1',
  },
  titleUnderline: {
    width: '52px',
    height: '3.5px',
    backgroundColor: '#2563eb',
    borderRadius: '2px',
  },
  subtitle: {
    color: '#6b7280',
    fontSize: '14px',
    lineHeight: '1.65',
    fontFamily: "'DM Sans', sans-serif",
    fontWeight: '300',
    paddingTop: '6px',
  },
  linkButton: {
    color: '#2563eb',
    fontSize: '14px',
    fontWeight: '500',
    fontFamily: "'DM Sans', sans-serif",
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: 0,
  },
  filterButtonBase: {
    fontSize: '14px',
    fontWeight: '400',
    color: '#6b7280',
    borderBottom: '2px solid transparent',
    paddingBottom: '3px',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    fontFamily: "'DM Sans', sans-serif",
  },
  filterButtonActive: {
    fontWeight: '600',
    color: '#0f1923',
    borderBottom: '2px solid #2563eb',
  },
  filterSeparator: {
    color: '#d1d5db',
    margin: '0 14px',
    fontSize: '16px',
  },
  cardsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '28px',
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: '10px',
    overflow: 'hidden',
    boxShadow: '0 2px 12px rgba(0,0,0,0.06)',
    border: '1px solid #e5e7eb',
  },
  imageWrap: {
    position: 'relative',
    overflow: 'hidden',
    height: '210px',
  },
  image: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    display: 'block',
  },
  badge: {
    position: 'absolute',
    top: '14px',
    left: '14px',
    color: '#fff',
    fontSize: '10px',
    fontWeight: '700',
    letterSpacing: '0.8px',
    padding: '4px 10px',
    borderRadius: '20px',
    fontFamily: "'DM Sans', sans-serif",
    textTransform: 'uppercase',
  },
  cardBody: {
    padding: '22px 22px 26px',
  },
  duration: {
    display: 'flex',
    alignItems: 'center',
    gap: '5px',
    color: '#9ca3af',
    fontSize: '12px',
    fontFamily: "'DM Sans', sans-serif",
    marginBottom: '8px',
  },
  cardTitle: {
    fontFamily: "'Playfair Display', Georgia, serif",
    fontSize: '19px',
    fontWeight: '700',
    color: '#0f1923',
    margin: '0 0 10px',
    lineHeight: '1.3',
  },
  cardDescription: {
    color: '#6b7280',
    fontSize: '13.5px',
    lineHeight: '1.65',
    fontFamily: "'DM Sans', sans-serif",
    fontWeight: '300',
    margin: '0 0 18px',
  },
  priceRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: '16px',
    borderTop: '1px solid #f3f4f6',
  },
  priceMeta: {
    fontSize: '10px',
    color: '#9ca3af',
    fontFamily: "'DM Sans', sans-serif",
    display: 'block',
    marginBottom: '2px',
  },
  priceValue: {
    fontSize: '18px',
    fontWeight: '700',
    color: '#0f1923',
    fontFamily: "'DM Sans', sans-serif",
  },
  priceSuffix: {
    fontSize: '11px',
    color: '#9ca3af',
    fontFamily: "'DM Sans', sans-serif",
    marginLeft: '3px',
  },
  ctaButton: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '5px',
    fontSize: '13px',
    fontWeight: '600',
    color: '#2563eb',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: 0,
  },
  emptyStateWrap: {
    gridColumn: '1 / -1',
    textAlign: 'center',
    padding: '40px 20px',
  },
  emptyStateText: {
    color: '#6b7280',
    fontSize: '16px',
  },
  loadingWrap: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: '400px',
  },
}
