export const tripDetailStyles = {
  page: {
    minHeight: '100vh',
    backgroundColor: '#f9fafb',
    display: 'flex',
    flexDirection: 'column',
  },
  pageShell: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
  },
  centerArea: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  centeredText: {
    textAlign: 'center',
  },
  contentWrap: {
    flex: 1,
  },
  container: {
    maxWidth: '1400px',
    margin: '0 auto',
    padding: '40px 20px',
  },
  backButton: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    color: '#2563eb',
    fontSize: '14px',
    fontWeight: '600',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: '0',
  },
  pageTitle: {
    fontSize: '42px',
    fontWeight: '700',
    color: '#0f1923',
    margin: '0 0 12px',
    lineHeight: '1.2',
  },
  pageSubtitle: {
    fontSize: '16px',
    color: '#6b7280',
    margin: '0',
    maxWidth: '600px',
  },
  heroCard: {
    backgroundColor: '#fff',
    borderRadius: '12px',
    overflow: 'hidden',
    marginBottom: '40px',
    boxShadow: '0 4px 20px rgba(0,0,0,0.08)',
  },
  heroImageWrap: {
    position: 'relative',
    height: '400px',
    overflow: 'hidden',
  },
  heroImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  heroOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    background: 'linear-gradient(to top, rgba(0,0,0,0.5), transparent)',
    padding: '40px 40px',
    color: '#fff',
  },
  heroTag: {
    padding: '6px 14px',
    borderRadius: '24px',
    fontSize: '11px',
    fontWeight: '700',
    letterSpacing: '0.6px',
    display: 'inline-block',
    textTransform: 'uppercase',
  },
  heroTitle: {
    fontSize: '36px',
    fontWeight: '700',
    margin: '0 0 12px',
    lineHeight: '1.2',
  },
  heroDescription: {
    margin: '0',
    fontSize: '16px',
    opacity: 0.95,
  },
  mainGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 380px',
    gap: '30px',
  },
  sectionTitle: {
    fontSize: '28px',
    fontWeight: '700',
    color: '#0f1923',
    marginBottom: '8px',
  },
  sectionSubtitle: {
    color: '#6b7280',
    margin: '0',
  },
  sidebar: {
    backgroundColor: '#fff',
    borderRadius: '12px',
    padding: '28px',
    boxShadow: '0 2px 12px rgba(0,0,0,0.06)',
    height: 'fit-content',
  },
  label: {
    color: '#9ca3af',
    fontSize: '12px',
    margin: '0 0 4px',
  },
  value: {
    fontSize: '18px',
    fontWeight: '700',
    color: '#0f1923',
    margin: '0',
  },
  largeValue: {
    fontSize: '24px',
    fontWeight: '700',
    color: '#0f1923',
    margin: '0',
  },
  helperText: {
    color: '#6b7280',
    fontSize: '12px',
    margin: '6px 0 0',
  },
  primaryAction: {
    width: '100%',
    padding: '14px',
    backgroundColor: '#2563eb',
    color: '#fff',
    border: 'none',
    borderRadius: '8px',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
    marginBottom: '12px',
    transition: 'background-color 0.3s ease',
  },
  secondaryAction: {
    width: '100%',
    padding: '14px',
    backgroundColor: 'transparent',
    color: '#2563eb',
    border: '1.5px solid #2563eb',
    borderRadius: '8px',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
  },
  includesItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
}
